# Generated by Django 5.1.4 on 2024-12-07 18:31

import django.db.models.deletion
import uuid
import versatileimagefield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant_type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225, unique=True)),
            ],
            options={
                'verbose_name': 'Variant Type',
                'verbose_name_plural': 'Variant Types',
                'db_table': 'variant_types',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ProductID', models.BigIntegerField(unique=True)),
                ('ProductCode', models.CharField(max_length=225, unique=True)),
                ('ProductName', models.CharField(max_length=225)),
                ('ProductImage', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='uploads/')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('UpdatedDate', models.DateTimeField(blank=True, null=True)),
                ('IsFavourite', models.BooleanField(default=False)),
                ('Active', models.BooleanField(default=True)),
                ('HSNCode', models.CharField(blank=True, max_length=225, null=True)),
                ('TotalStock', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, null=True)),
                ('CreatedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'products_product',
                'ordering': ('-CreatedDate', 'ProductID'),
                'unique_together': {('ProductCode', 'ProductID')},
            },
        ),
        migrations.CreateModel(
            name='SubVariant_types',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225, unique=True)),
                ('variant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subvariant_types', to='product_app.variant_type')),
            ],
            options={
                'verbose_name': 'Subvariant Type',
                'verbose_name_plural': 'Subvariant Types',
                'db_table': 'subvariant_types',
            },
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product_app.products')),
                ('variant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product_app.variant_type')),
            ],
            options={
                'db_table': 'product_variants',
                'unique_together': {('product', 'variant_name')},
            },
        ),
        migrations.CreateModel(
            name='SubVariants',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subvariants', to='product_app.subvariant_types')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subvariants', to='product_app.variants')),
            ],
            options={
                'db_table': 'products_subvariants',
                'unique_together': {('variant', 'options')},
            },
        ),
    ]
