# Generated by Django 5.1.4 on 2024-12-07 11:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product_app.products')),
            ],
            options={
                'db_table': 'product_variants',
                'unique_together': {('product', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SubVariants',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('options', models.CharField(max_length=225)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subvariants', to='product_app.variants')),
            ],
            options={
                'db_table': 'products_subvariants',
                'unique_together': {('variant', 'options')},
            },
        ),
    ]
