# Generated by Django 5.1.4 on 2024-12-07 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='variant_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product_app.variant_type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variants',
            name='variant_name',
            field=models.CharField(max_length=225),
        ),
    ]
