# Generated by Django 5.1.4 on 2024-12-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_variants_variant_type_alter_variants_variant_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variants',
            unique_together={('product', 'variant_type')},
        ),
    ]
