# Generated by Django 5.1.4 on 2024-12-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_alter_variants_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='variant_name',
        ),
    ]
